eol = true
name = "node"
title = "Node.js"
intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/drivers/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
]

toc_landing_pages = [
    "/fundamentals/authentication",
    "/fundamentals",
    "/fundamentals/connection",
    "/fundamentals/crud",
    "/fundamentals/bson",
    "/usage-examples",
    "/quick-start",
    "/aggregation-tutorials",
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
version = "5.5"
api = "https://mongodb.github.io/node-mongodb-native/{+version+}"
min-node-version = "v12"
driver-long = "MongoDB Node.js driver"
driver-short = "Node.js driver"
mdb-server = "MongoDB Server"
stable-api = "Stable API"
driver-url = "https://www.mongodb.com/docs/drivers/node/current"

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <{+driver-url+}>`__ to learn how to `upgrade your version of the {+driver-short+} <{+driver-url+}/upgrade>`__.\
    """
