eol = true
name = "node"
title = "Node.js"
intersphinx = ["https://mongodb.com/docs/manual/objects.inv",
              "https://mongodb.com/docs/drivers/objects.inv"]

toc_landing_pages = [
    "/fundamentals/authentication",
    "/fundamentals",
    "/fundamentals/connection",
    "/fundamentals/crud",
    "/fundamentals/bson",
    "/usage-examples",
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
version = "3.6"
package-name-org = "mongodb-org"
pgp-version = "{+version+}"
api = "https://mongodb.github.io/node-mongodb-native/{+version+}"
mongosh = "``mongosh``"
driver = "node"
driver-long = "MongoDB Node.js driver"
driver-short = "Node.js driver"
mdb-server = "MongoDB Server"

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <link>`__ to learn how to `upgrade your version of [product name] <link>`__.\
    """
